const API = '/api/football';
const leagues = [
  ['eng.1', 'لیگ برتر انگلیس'], ['esp.1', 'لالیگا'], ['ita.1', 'سری آ ایتالیا'],
  ['ger.1', 'بوندس‌لیگا'], ['fra.1', 'لیگ یک فرانسه'], ['uefa.champions', 'لیگ قهرمانان اروپا']
];
const fallbackNews = [
  {headline:'آخرین تحولات فوتبال اروپا؛ فصل جدید وارد مرحله‌ای هیجان‌انگیز شد',description:'مهم‌ترین خبرها و اتفاقات روز فوتبال اروپا را در یک صفحه دنبال کنید.',published:'همین حالا',image:'https://images.unsplash.com/photo-1522778119026-d647f0596c20?auto=format&fit=crop&w=900&q=80'},
  {headline:'ستاره‌های بزرگ آماده هفته جدید فوتبال هستند',description:'برنامه مسابقات، فرم تیم‌ها و اتفاقات مهم را قبل از شروع بازی‌ها ببینید.',published:'امروز',image:'https://images.unsplash.com/photo-1574629810360-7efbbe195018?auto=format&fit=crop&w=900&q=80'},
  {headline:'نبردهای حساس لیگ‌های بزرگ اروپا نزدیک است',description:'جدول، نتایج و آمار تیم‌های محبوب را در مرکز مسابقات دنبال کنید.',published:'امروز',image:'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?auto=format&fit=crop&w=900&q=80'}
];
const teams = [
  ['رئال مادرید','https://media.api-sports.io/football/teams/541.png'],['بارسلونا','https://media.api-sports.io/football/teams/529.png'],
  ['منچسترسیتی','https://media.api-sports.io/football/teams/50.png'],['لیورپول','https://media.api-sports.io/football/teams/40.png'],
  ['منچستریونایتد','https://media.api-sports.io/football/teams/33.png'],['بایرن مونیخ','https://media.api-sports.io/football/teams/157.png'],
  ['اینتر','https://media.api-sports.io/football/teams/505.png'],['آرسنال','https://media.api-sports.io/football/teams/42.png'],['چلسی','https://media.api-sports.io/football/teams/49.png']
];
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let newsData=[...fallbackNews], matchData=[], standingsData=[];
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function formatTime(d){try{return new Intl.DateTimeFormat('fa-IR',{hour:'2-digit',minute:'2-digit'}).format(new Date(d));}catch{return '';}}
function formatDate(d){try{return new Intl.DateTimeFormat('fa-IR',{year:'numeric',month:'long',day:'numeric'}).format(new Date(d));}catch{return 'امروز';}}
async function getJson(url){const r=await fetch(url,{headers:{accept:'application/json'},cache:'no-store'});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||`HTTP ${r.status}`);return data;}
function translateStatus(v=''){const s=String(v).toLowerCase();if(s.includes('postponed'))return 'به تعویق افتاده';if(s.includes('cancel'))return 'لغو شده';if(s.includes('half'))return 'پایان نیمه اول';if(s.includes('finish')||s.includes('final'))return 'پایان بازی';if(s.includes('extra'))return 'وقت اضافه';if(s.includes('penalty'))return 'ضربات پنالتی';if(s.includes('scheduled')||s.includes('not started')||s==='ns')return 'برنامه‌ریزی‌شده';return v||'در انتظار';}
function normalizeEvents(data,leagueName=''){return (data.events||[]).map(e=>{const c=e.competitions?.[0]||{},cs=c.competitors||[],h=cs.find(x=>x.homeAway==='home')||cs[0]||{},a=cs.find(x=>x.homeAway==='away')||cs[1]||{};return{id:String(e.id||''),league:leagueName||e.league?.name||'',date:e.date,status:translateStatus(e.status?.type?.shortDetail||e.status?.type?.detail),state:e.status?.type?.state||'pre',home:{name:h.team?.displayName||'تیم میزبان',short:h.team?.shortDisplayName||h.team?.displayName||'',logo:h.team?.logo||'',score:h.score??'0'},away:{name:a.team?.displayName||'تیم مهمان',short:a.team?.shortDisplayName||a.team?.displayName||'',logo:a.team?.logo||'',score:a.score??'0'}};});}
async function loadMatches(){const rs=await Promise.all(leagues.map(async([id,name])=>{try{return normalizeEvents(await getJson(`${API}/${id}/fixtures`),name);}catch(e){console.warn('fixtures',id,e);return[];}}));matchData=rs.flat().sort((a,b)=>new Date(a.date)-new Date(b.date));renderMatches($$('.filter.active')[0]?.dataset.league||'all');renderScoreList();updateTicker();}
async function loadLive(){try{const live=normalizeEvents(await getJson(`${API}/live`));const ids=new Set(live.map(x=>x.id));const rest=matchData.filter(x=>!ids.has(x.id));matchData=[...live,...rest].sort((a,b)=>new Date(a.date)-new Date(b.date));renderMatches($$('.filter.active')[0]?.dataset.league||'all');renderScoreList();updateTicker();}catch(e){console.warn('live',e);}}
function matchHTML(m){const live=m.state==='in';return `<article class="match-card"><div class="match-meta"><span>${esc(m.league)}</span><span>${live?'● زنده':formatTime(m.date)}</span></div><div class="match-teams"><div class="club"><img src="${esc(m.home.logo)}" alt="" onerror="this.style.visibility='hidden'"><strong>${esc(m.home.name)}</strong></div><div class="match-score">${m.state==='pre'?'—':`${esc(m.home.score)} - ${esc(m.away.score)}`}<small>${esc(m.status)}</small></div><div class="club"><img src="${esc(m.away.logo)}" alt="" onerror="this.style.visibility='hidden'"><strong>${esc(m.away.name)}</strong></div></div></article>`;}
function renderMatches(filter='all'){const ln=leagues.find(x=>x[0]===filter)?.[1],data=filter==='all'?matchData:matchData.filter(m=>m.league===ln);$('#allMatches').innerHTML=data.length?data.slice(0,24).map(matchHTML).join(''):'<div class="empty-state">برای این رقابت در بازه فعلی مسابقه‌ای پیدا نشد.</div>';const live=matchData.filter(m=>m.state==='in').slice(0,4);$('#liveMatches').innerHTML=live.length?live.map(m=>`<div class="live-item"><div class="team"><strong>${esc(m.home.short||m.home.name)}</strong></div><div class="score">${esc(m.home.score)} - ${esc(m.away.score)}<small>● ${esc(m.status)}</small></div><div class="team"><strong>${esc(m.away.short||m.away.name)}</strong></div></div>`).join(''):'<div class="live-item"><div class="team"><strong>فعلاً بازی زنده‌ای در جریان نیست</strong></div><div class="score">—</div><div class="team">بازی‌های پیش‌رو در مرکز مسابقات</div></div>';}
function renderScoreList(){const d=matchData.slice(0,7);$('#scoreList').innerHTML=d.length?d.map(m=>`<div class="score-row"><div class="home">${esc(m.home.short||m.home.name)}</div><div class="score-num">${m.state==='pre'?'—':`${esc(m.home.score)}-${esc(m.away.score)}`}<small>${m.state==='in'?'زنده':formatTime(m.date)}</small></div><div class="away">${esc(m.away.short||m.away.name)}</div></div>`).join(''):'<div class="loading">برنامه مسابقات در دسترس نیست.</div>';}
async function loadNews(){try{const d=await getJson(`${API}/eng.1/news?limit=12`);if(d.articles?.length)newsData=d.articles;}catch{}renderNews();const n=newsData[0]||fallbackNews[0];$('#heroTitle').textContent=n.headline;$('#heroSummary').textContent=n.description;$('#heroCard').style.backgroundImage=`linear-gradient(90deg,rgba(3,10,8,.96) 0%,rgba(3,10,8,.72) 45%,rgba(3,10,8,.12)),url('${n.image}')`;$('#latestNews').innerHTML=newsData.slice(0,5).map(newsMini).join('');}
function newsMini(n){return `<a class="latest-item" href="${esc(n.link||'#')}" target="_blank" rel="noopener"><img src="${esc(n.image)}" alt="تصویر خبر" loading="lazy" onerror="this.src='${fallbackNews[0].image}'"><div><h3>${esc(n.headline)}</h3><small>${esc(n.published?formatDate(n.published):'امروز')}</small></div></a>`;}
function renderNews(){$('#newsGrid').innerHTML=newsData.slice(0,6).map(n=>`<article class="news-card"><img src="${esc(n.image)}" alt="تصویر خبر" loading="lazy"><div class="news-card-body"><h3>${esc(n.headline)}</h3><p>${esc(n.description)}</p><div class="news-meta"><span>خبر فوتبال</span><span>● تازه</span></div></div></article>`).join('');}
async function loadStandings(){try{const d=await getJson(`${API}/eng.1/standings`);standingsData=d.standings||[];}catch(e){console.warn('standings',e);standingsData=[];}renderStandings();}
function renderStandings(){if(!standingsData.length){$('#standings').innerHTML='<div class="loading">جدول لیگ برتر فعلاً از سرویس فوتبال دریافت نشد.</div>';return;}$('#standings').innerHTML='<div class="table-row head"><span>رتبه</span><span>تیم</span><span>بازی</span><span>تفاضل</span><span>امتیاز</span></div>'+standingsData.slice(0,8).map(e=>`<div class="table-row"><span class="rank">${e.rank}</span><strong>${esc(e.team?.name||'')}</strong><span>${e.all?.played??0}</span><span>${(e.all?.goals?.for??0)-(e.all?.goals?.against??0)>=0?'+':''}${(e.all?.goals?.for??0)-(e.all?.goals?.against??0)}</span><span>${e.points??0}</span></div>`).join('');}
function renderTeams(){$('#teamsRow').innerHTML=teams.map(t=>`<a class="team-card" href="#matches"><img src="${esc(t[1])}" alt="${esc(t[0])}" onerror="this.style.opacity=.2"><span>${esc(t[0])}</span></a>`).join('');}
function updateTicker(){const live=matchData.find(m=>m.state==='in'),next=matchData.find(m=>m.state==='pre');$('#tickerText').textContent=live?`${live.home.name} ${live.home.score} - ${live.away.score} ${live.away.name} · ${live.status}`:next?`بازی بعدی: ${next.home.name} - ${next.away.name} · ${formatTime(next.date)}`:'مرکز مسابقات کیکورا آماده است';}
function toast(text){const t=document.createElement('div');t.className='toast';t.textContent=text;document.body.appendChild(t);setTimeout(()=>t.remove(),2600);}
function setup(){renderTeams();loadNews();loadMatches();loadLive();loadStandings();setInterval(loadLive,20*60*1000);setInterval(loadMatches,12*60*60*1000);setInterval(loadStandings,24*60*60*1000);$$('[data-scroll]').forEach(b=>b.addEventListener('click',()=>document.querySelector(b.dataset.scroll)?.scrollIntoView({behavior:'smooth'})));$$('.filter').forEach(b=>b.addEventListener('click',()=>{$$('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderMatches(b.dataset.league);}));$('#themeBtn').onclick=()=>{document.body.classList.toggle('light');localStorage.setItem('kickora-theme',document.body.classList.contains('light')?'light':'dark');};if(localStorage.getItem('kickora-theme')==='light')document.body.classList.add('light');$('#alertToggle').onclick=()=>{const on=$('#alertToggle').textContent==='●';$('#alertToggle').textContent=on?'○':'●';toast(on?'اعلان‌ها خاموش شد':'اعلان‌های کیکورا فعال شد');};$$('.tab').forEach(b=>b.onclick=()=>{$$('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');if(b.dataset.news==='popular'){$('#newsGrid').innerHTML=[...newsData].reverse().slice(0,6).map(n=>`<article class="news-card"><img src="${esc(n.image)}" alt="تصویر خبر"><div class="news-card-body"><h3>${esc(n.headline)}</h3><p>${esc(n.description)}</p><div class="news-meta"><span>پربازدید</span><span>🔥</span></div></div></article>`).join('');}else renderNews();});}
document.addEventListener('DOMContentLoaded',setup);
