const COMPETITIONS = {
  'eng.1': { id: 39, name: 'لیگ برتر انگلیس' },
  'esp.1': { id: 140, name: 'لالیگا' },
  'ita.1': { id: 135, name: 'سری آ ایتالیا' },
  'ger.1': { id: 78, name: 'بوندس‌لیگا' },
  'fra.1': { id: 61, name: 'لیگ یک فرانسه' },
  'uefa.champions': { id: 2, name: 'لیگ قهرمانان اروپا' },
};
const API_BASE = 'https://v3.football.api-sports.io';
const LIVE_TTL = 1200;
const FIXTURES_TTL = 86400;
const STANDINGS_TTL = 86400;
const TEAMS_TTL = 21600;
const TEAM_TTL = 21600;
const NEWS_TTL = 600;

function json(data, status = 200, cacheSeconds = 30, extra = {}) { return new Response(JSON.stringify(data), { status, headers: { 'content-type': 'application/json; charset=utf-8', 'cache-control': `public, max-age=${cacheSeconds}`, 'access-control-allow-origin': '*', 'access-control-allow-methods': 'GET, OPTIONS', 'access-control-allow-headers': 'content-type', ...extra } }); }
function seasonFor(date = new Date()) { const m=date.getUTCMonth()+1,y=date.getUTCFullYear(); return m>=7?y:y-1; }
function dateOnly(v){return /^\d{4}-\d{2}-\d{2}$/.test(v||'')?v:'';}
function dateOffset(days){const d=new Date();d.setUTCDate(d.getUTCDate()+days);return d.toISOString().slice(0,10);}
function competitionFromPath(path){const p=path.split('/').filter(Boolean),i=p.indexOf('football');return i>=0&&COMPETITIONS[p[i+1]]?p[i+1]:'eng.1';}
function statusInfo(s=''){const live=new Set(['1H','HT','2H','ET','BT','P','LIVE']),done=new Set(['FT','AET','PEN','AWD','WO','ABD']),delay=new Set(['PST','CANC']);if(live.has(s))return{state:'in',text:s==='HT'?'پایان نیمه اول':s==='P'?'ضربات پنالتی':'زنده'};if(done.has(s))return{state:'post',text:s==='PEN'?'پایان با پنالتی':'پایان بازی'};if(delay.has(s))return{state:'post',text:s==='PST'?'به تعویق افتاده':'لغو شده'};return{state:'pre',text:'برنامه‌ریزی‌شده'};}
function normalizeFixture(x,name){const f=x.fixture||{},h=x.teams?.home||{},a=x.teams?.away||{},s=statusInfo(f.status?.short);return{id:String(f.id||''),league:name||x.league?.name||'فوتبال',date:f.date||'',timestamp:f.timestamp||0,status:s.text,state:s.state,home:{name:h.name||'تیم میزبان',short:h.name||'',logo:h.logo||'',score:x.goals?.home??0},away:{name:a.name||'تیم مهمان',short:a.name||'',logo:a.logo||'',score:x.goals?.away??0}};}
function normalizeStandings(data){const groups=data?.response?.[0]?.league?.standings||[];return groups.flatMap(g=>Array.isArray(g)?g:[]).map(r=>({rank:r.rank,team:{name:r.team?.name||'تیم',logo:r.team?.logo||''},points:r.points??0,all:{played:r.all?.played??0,goals:{for:r.all?.goals?.for??0,against:r.all?.goals?.against??0}}})).sort((a,b)=>(a.rank??999)-(b.rank??999));}
function normalizeTeam(x){const t=x?.team||{},v=x?.venue||{};return{id:String(t.id||''),name:t.name||'',code:t.code||'',country:t.country||'',founded:t.founded||null,national:Boolean(t.national),logo:t.logo||'',venue:{id:v.id||null,name:v.name||'',address:v.address||'',city:v.city||'',capacity:v.capacity||null,surface:v.surface||'',image:v.image||''}};}
async function apiFootball(env,path,params={}){if(!env.API_FOOTBALL_KEY)throw new Error('API_FOOTBALL_KEY is not configured');const u=new URL(API_BASE+path);Object.entries(params).forEach(([k,v])=>{if(v!==undefined&&v!==null&&v!=='')u.searchParams.set(k,String(v));});const r=await fetch(u,{headers:{'x-apisports-key':env.API_FOOTBALL_KEY,accept:'application/json'}}),d=await r.json().catch(()=>({}));if(!r.ok||(d.errors&&Object.keys(d.errors).length)){const e=typeof d.errors==='object'?Object.values(d.errors).join('; '):`HTTP ${r.status}`;throw new Error(e||`HTTP ${r.status}`);}return{data:d,remaining:r.headers.get('x-ratelimit-requests-remaining')||''};}
async function cachedFetch(env,path,params,ttl,transform){const u=new URL(API_BASE+path);Object.entries(params).forEach(([k,v])=>{if(v!==undefined&&v!==null&&v!=='')u.searchParams.set(k,String(v));});const key=new Request(u.toString()),cache=caches.default,cached=await cache.match(key);if(cached)return new Response(cached.body,cached);const r=await apiFootball(env,path,params),out=json(transform(r.data),200,ttl,{'x-kickorax-data-source':'api-football',...(r.remaining?{'x-api-requests-remaining':r.remaining}:{})});await cache.put(key,out.clone());return out;}
async function handleNews(request){const n=Math.min(Number(new URL(request.url).searchParams.get('limit')||12),20),u=`https://site.api.espn.com/apis/site/v2/sports/soccer/eng.1/news?limit=${n}`,key=new Request(u),cache=caches.default,cached=await cache.match(key);if(cached)return new Response(cached.body,cached);const r=await fetch(u,{headers:{accept:'application/json'}});if(!r.ok)throw new Error(`News provider HTTP ${r.status}`);const d=await r.json(),articles=(d.articles||[]).map(x=>({headline:x.headline||x.title||'خبر فوتبال',description:x.description||x.summary||'',published:x.published||'',image:x.images?.[0]?.url||'',link:x.links?.web?.href||'#'})),out=json({articles},200,NEWS_TTL,{'x-kickorax-data-source':'espn-news'});await cache.put(key,out.clone());return out;}
async function handleTeam(env,request){const url=new URL(request.url),id=String(url.searchParams.get('id')||'');if(!/^\d+$/.test(id))return json({ok:false,error:'A valid numeric team id is required.'},400,30);const season=seasonFor();const [teamRes,squadRes,fixturesRes,statsRes]=await Promise.all([apiFootball(env,'/teams',{id}),apiFootball(env,'/players/squads',{team:id}),apiFootball(env,'/fixtures',{team:id,season,next:4,last:4}),apiFootball(env,'/teams/statistics',{league:39,season,team:id}).catch(()=>({data:{response:[]}}))]);const raw=teamRes.data.response?.[0];if(!raw)return json({ok:false,error:'Team not found.'},404,60);const team=normalizeTeam(raw),squad=(squadRes.data.response?.[0]?.players||[]).map(p=>({id:p.id,name:p.name,age:p.age,number:p.number,position:p.position,photo:p.photo||''})),fixtures=(fixturesRes.data.response||[]).map(x=>({id:x.fixture?.id,date:x.fixture?.date,status:x.fixture?.status?.short||'NS',home:{name:x.teams?.home?.name||'',logo:x.teams?.home?.logo||''},away:{name:x.teams?.away?.name||'',logo:x.teams?.away?.logo||''},goals:{home:x.goals?.home,away:x.goals?.away}})),statistics=statsRes.data.response?.[0]?.statistics||{};return json({team,squad,fixtures,statistics},200,TEAM_TTL,{'x-kickorax-data-source':'api-football'});}
export async function onRequestGet(context){const{request,env}=context,url=new URL(request.url),path=url.pathname;if(path.endsWith('/health'))return json({ok:Boolean(env.API_FOOTBALL_KEY),provider:'api-football',secret:'API_FOOTBALL_KEY'},200,30);try{if(!env.API_FOOTBALL_KEY)return json({ok:false,error:'API_FOOTBALL_KEY is not configured in this Worker.'},503,30);if(path.endsWith('/news'))return await handleNews(request);if(path.endsWith('/team'))return await handleTeam(env,request);const key=competitionFromPath(path),c=COMPETITIONS[key],season=seasonFor();if(path.endsWith('/live'))return await cachedFetch(env,'/fixtures',{live:'all'},LIVE_TTL,d=>({events:(d.response||[]).map(x=>normalizeFixture(x,x.league?.name))}));if(path.endsWith('/fixtures'))return await cachedFetch(env,'/fixtures',{league:c.id,season,from:dateOnly(url.searchParams.get('from'))||dateOffset(-2),to:dateOnly(url.searchParams.get('to'))||dateOffset(7),timezone:'Asia/Tehran'},FIXTURES_TTL,d=>({events:(d.response||[]).map(x=>normalizeFixture(x,c.name))}));if(path.endsWith('/standings'))return await cachedFetch(env,'/standings',{league:c.id,season},STANDINGS_TTL,d=>({standings:normalizeStandings(d)}));if(path.endsWith('/teams'))return await cachedFetch(env,'/teams',{league:c.id,season},TEAMS_TTL,d=>({teams:(d.response||[]).map(x=>({team:x.team,venue:x.venue}))}));if(path.endsWith('/competitions'))return json({competitions:Object.entries(COMPETITIONS).map(([code,v])=>({code,...v}))},200,21600);return json({ok:false,error:'Unknown football API route'},404,30);}catch(e){return json({ok:false,error:e instanceof Error?e.message:'Football provider error'},502,15);}}
export async function onRequestOptions(){return new Response(null,{status:204,headers:{'access-control-allow-origin':'*','access-control-allow-methods':'GET, OPTIONS','access-control-allow-headers':'content-type','access-control-max-age':'86400'}});}
